version: "3.8"

services:
  app:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: irons-postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: "no"
    volumes:
      - db-data:/var/lib/postgresql/data/
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=password
    restart: "no"
    volumes:
      - pgadmin:/root/.pgadmin
volumes:
  db-data:
  pgadmin:
